apiVersion: apps/v1
kind: Deployment
metadata:
  name: netlify-clone-deployment
  labels:
    app: netlify-clone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netlify-clone
  template:
    metadata:
      labels:
        app: netlify-clone
    spec:
      containers:
      - name: netlify-clone
        image: your-image-name:latest
        ports:
        - containerPort: 80

        
---

apiVersion: v1
kind: Service
metadata:
  name: netlify-clone-service
spec:
  selector:
    app: netlify-clone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
