apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
  labels:
    app: nextjs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: ambati2019/nextjs-app
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: database_host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: database_port
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: database_name
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthz  # Define a health endpoint in your app
              port: 3000
            initialDelaySeconds: 30  # Delay before probing starts
            periodSeconds: 10        # How often to probe
            failureThreshold: 3       # How many failures before considering the container unhealthy

         readinessProbe:
            httpGet:
              path: /healthz  # Same as livenessProbe, define a health endpoint
              port: 3000
            initialDelaySeconds: 5   # Shorter delay for readiness check
            periodSeconds: 5         # Period between probes
            failureThreshold: 3      # Fail after 3 consecutive failures
   

---

apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Ensure this matches the container's exposed port
  type: NodePort
