apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
  labels:
    app: nextjs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs
        image: ambati2019/nextjs-app
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                 key: database_host
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: database_port
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: database_name
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
      resources:
        limits:
           memory: "512Mi"
           cpu: "500m        

        
---

apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: nodeport
