apiVersion: apps/v1
kind: Deployment
metadata:
  name: netlify-clone-deployment
  labels:
    app: netlify-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netlify-clone
  template:
    metadata:
      labels:
        app: netlify-clone
    spec:
      containers:
      - name: netlify-clone
        image: ambati2019/nextjs-app
        ports:
        - containerPort: 80
        env:
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                 key: database_host
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: database_port
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: database_name
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password

        
---

apiVersion: v1
kind: Service
metadata:
  name: netlify-clone-service
spec:
  selector:
    app: netlify-clone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: nodeport
